include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - apps/**/lib/firebase_options.dart
    - apps/**/lib/firebase_options_dev.dart
    - apps/**/lib/firebase_options_stg.dart
    - .github/workflows/**

  strong-mode:
    implicit-dynamic: false

  errors:
    invalid_annotation_target: ignore
    todo: ignore
    fix_me: warning
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    depend_on_referenced_packages: ignore

linter:
  rules:
    always_use_package_imports: true
    avoid_empty_else: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    close_sinks: true
    collection_methods_unrelated_type: true
    control_flow_in_finally: true
    deprecated_member_use_from_same_package: true
    empty_statements: true
    hash_and_equals: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    no_wildcard_variable_uses: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    use_build_context_synchronously: false
    use_key_in_widget_constructors: true
    valid_regexps: true
    prefer_const_constructors: true

    camel_case_types: true
    prefer_single_quotes: true

    depend_on_referenced_packages: true
    package_names: true
    require_trailing_commas: true
    lines_longer_than_80_chars: ignore
    implementation_imports: true
