name: core_storage
description: core storage package.
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: "^3.32.8"

dependencies:
  shared_preferences: 2.5.3
  flutter_secure_storage: 9.2.4

  core_util:
    path: ../util

dev_dependencies:
  build_runner: 2.7.0
  injectable_generator: 2.8.1
