name: presentation
description: fooponote presentation package.
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: "^3.32.8"

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ../domain

  core_bloc:
    path: ../../core/bloc
  core_util:
    path: ../../core/util
