name: tool_base_component
description: tool base component package.
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: "^3.32.8"

dependencies:
  flutter:
    sdk: flutter
  core_util:
    path: ../../../core/util
  tool_base_theme:
    path: ../theme

dev_dependencies:
  build_runner: 2.7.0
  flutter_gen_runner: 5.11.0

flutter_gen:
  output: lib/gen/
  line_length: 120

flutter:
  assets:
    - assets/images/svgs/
