name: core_util
description: core util package.
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: "^3.32.8"

dependencies:
  flutter:
    sdk: flutter

  custom_refresh_indicator: 4.0.1
  event_bus: 2.0.1
  firebase_core: 4.0.0
  firebase_remote_config: 6.0.0
  flutter_svg: 2.2.0
  intl: 0.20.2
  shimmer: 3.0.0
  gap: 3.0.1
  get_it: 8.2.0
  injectable: 2.5.1
  dartz: 0.10.1
  equatable: 2.0.7
