name: core_util
description: core util package.
publish_to: none

environment:
  sdk: 3.8.1
  flutter: 3.32.8

dependencies:
  flutter:
    sdk: flutter

  custom_refresh_indicator: 4.0.1
  event_bus: 2.0.1
  firebase_core: 4.0.0
  firebase_remote_config: 6.0.0
  flutter_svg: 2.2.0
  intl: 0.20.2
  shimmer: 3.0.0
  gap: 3.0.1
